In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split

In [2]:
#Reading data without outliers
df = pd.read_csv('credit_data_process-2.csv')
df.head()

Unnamed: 0  Month  Occupation  Type_of_Loan  Credit_Mix  \
0           1      2          12           128           1   
1           2      6          12           128           1   
2           3      0          12           128           1   
3           4      7          12           128           1   
4           5      5          12           128           1   

   Payment_of_Min_Amount  Payment_Behaviour  Credit_Score   Age  \
0                      1                  4             0  23.0   
1                      1                  5             0   0.0   
2                      1                  6             0  23.0   
3                      1                  2             0  23.0   
4                      1                  0             0  23.0   

   Annual_Income  ...  Delay_from_due_date  Num_of_Delayed_Payment  \
0       19114.12  ...                  0.0               31.033317   
1       19114.12  ...                  3.0                7.000000   
2       19114.12  ...                  5.0                4.000000   
3       19114.12  ...                  6.0               31.033317   
4       19114.12  ...                  8.0                4.000000   

   Changed_Credit_Limit  Num_Credit_Inquiries  Outstanding_Debt  \
0             11.270000                   4.0            809.98   
1             10.389016                   4.0            809.98   
2              6.270000                   4.0            809.98   
3             11.270000                   4.0            809.98   
4              9.270000                   4.0            809.98   

   Credit_Utilization_Ratio  Total_EMI_per_month  Amount_invested_monthly  \
0                 31.944960            49.574949               118.280222   
1                 28.609352            49.574949                81.699521   
2                 31.377862            49.574949               199.458074   
3                 24.797347            49.574949                41.420153   
4                 27.262259            49.574949                62.430172   

   Monthly_Balance  Credit_History_Months  
0       284.629163             220.840847  
1       331.209863             267.000000  
2       223.451310             268.000000  
3       341.489231             269.000000  
4       340.479212             270.000000  

[5 rows x 25 columns]

In [3]:
df = df.drop(['Unnamed: 0'],axis=1)

In [4]:
# Selecting Top 10 features from the feature selection
# Top 10 features
# 1. Outstanding_Debt  
# 2. Annual_Income
# 3. Total_EMI_per_month 
# 4. Type_of_Loan
# 5. Interest_Rate
# 6. Credit_Mix
# 7. Delay_from_due_date  
# 8. Num_Credit_Inquiries
# 9. Payment_of_Min_Amount 
# 10. Num_Credit_Card 

In [5]:
df_1 = df[['Type_of_Loan', 'Credit_Mix', 'Annual_Income', 'Monthly_Inhand_Salary',
       'Num_Credit_Card', 'Interest_Rate', 'Delay_from_due_date',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Total_EMI_per_month','Credit_Score']]

In [6]:
X = df_1.drop(['Credit_Score'],axis=1)
y = df_1['Credit_Score']

In [7]:
#Min Max scaling 
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
model = scalar.fit(X)
scaled_X = model.transform(X)
scaled_X


array([[0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       [0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       [0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       ...,
       [0.10912286, 0.33333333, 0.23629269, ..., 0.16666667, 0.12629543,
        0.09816544],
       [0.10912286, 0.33333333, 0.23629269, ..., 0.16666667, 0.12629543,
        0.09816544],
       [0.10912286, 0.33333333, 0.22123968, ..., 0.16666667, 0.12629543,
        0.09816544]])

In [8]:
#splitting data into train,validation and test datasets
X_train, X_rem, y_train, y_rem = train_test_split(scaled_X,y, train_size=0.5,random_state=42)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5,random_state=42)

In [9]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [10]:
rfc.fit(X_train,y_train)
#model on the validation dataset
y_valid_pred = rfc.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.76312


In [11]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV

In [12]:
# model on the test dataset
y_test_pred = rfc.predict(X_test)
accu = accuracy_score(y_test,y_test_pred)

print(f"The accuracy for the model is {accu}")

The accuracy for the model is 0.76024


# finding best hyperparameters using Randomized  searchcv

In [ ]:
random_grid = {'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400],
               'max_features': ['auto', 'sqrt'],
               'max_depth': [10, 20, 30, 40, 50, 60, 70]
               'min_samples_split': [2, 5, 10,12,15,18,20],
               'min_samples_leaf': [1, 2, 4],
               'bootstrap': [True, False]}
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train,y_train)


In [ ]:
rf_random.best_params_

In [10]:
rf_model = RandomForestClassifier(n_estimators=1000,max_features="auto",
                                  max_depth=20,min_samples_split=12,min_samples_leaf=2,bootstrap=True)
rf_model.fit(X_train,y_train)

C:\Users\Student\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(max_depth=20, max_features='auto', min_samples_leaf=2,
                       min_samples_split=12, n_estimators=1000)

In [14]:
#best model on the validation data
y_valid_pred = rf_model.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.76056


In [11]:
#best model on the test data
y_test_pred = rf_model.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.75352


In [12]:
# Confusion matrx for the model
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[ 2897    66  1454]
 [  272  5471  1494]
 [ 1174  1702 10470]]


In [13]:
#Classification Report for the model
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.67      0.66      0.66      4417
           1       0.76      0.76      0.76      7237
           2       0.78      0.78      0.78     13346

    accuracy                           0.75     25000
   macro avg       0.73      0.73      0.73     25000
weighted avg       0.75      0.75      0.75     25000



# PCA model

In [14]:
#Reading data without outliers
df_pca = pd.read_csv('Credit_data_PCA.csv')
df_pca.head()

Unnamed: 0         0         1         2         3         4         5  \
0           0 -0.136363 -0.370934  0.041678  0.263842 -0.222105  0.292258   
1           1 -0.226325 -0.463382  0.151887  0.296798  0.345578  0.304052   
2           2 -0.273298 -0.478896  0.422737  0.295270 -0.517704  0.286965   
3           3 -0.126936 -0.375277 -0.303028  0.312867  0.500363  0.306469   
4           4 -0.337219 -0.249693 -0.537153  0.358871  0.219459  0.308859   

          6         7         8  ...        10        11        12        13  \
0  0.251458 -0.438477 -0.190560  ...  0.547227 -0.097278 -0.341116 -0.124602   
1  0.211837 -0.472029 -0.316839  ... -0.020493 -0.073904 -0.188365 -0.469507   
2  0.194752 -0.482383 -0.322554  ... -0.117989  0.019139 -0.105781 -0.162512   
3  0.272134 -0.428103 -0.231405  ...  0.576941  0.048185 -0.210290 -0.179118   
4  0.244402 -0.453667 -0.368670  ... -0.019088  0.321884 -0.029550 -0.192756   

         14        15        16        17        18  Credit_Score  
0 -0.107184 -0.040613 -0.066402  0.042967  0.056982             0  
1  0.041760 -0.076142 -0.225868 -0.041018  0.090555             0  
2 -0.098846 -0.021087 -0.085814 -0.016029  0.084190             0  
3  0.028326 -0.181783 -0.088332  0.009019  0.133855             0  
4 -0.054961 -0.077647 -0.081890 -0.034598  0.105237             0  

[5 rows x 21 columns]

In [15]:
X = df_pca.drop(['Credit_Score'],axis=1)
y = df_pca['Credit_Score']

In [16]:
#splitting data into train,validation and test datasets
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.5,random_state=42)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5,random_state=42)

In [17]:
# shapes of train,validation and  test split
print(X_train.shape), print(y_train.shape)
print(X_valid.shape), print(y_valid.shape)
print(X_test.shape), print(y_test.shape)

(49999, 20)
(49999,)
(25000, 20)
(25000,)
(25000, 20)
(25000,)


(None, None)

In [18]:
X = df_pca.drop(['Credit_Score'],axis=1)
y = df_pca['Credit_Score']

In [21]:
rf = RandomForestClassifier()

In [22]:
rf.fit(X_train,y_train)
#model on the validation dataset
y_valid_pred = rf.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.69468


In [23]:
# model on the test dataset
y_test_pred = rf.predict(X_test)
accu = accuracy_score(y_test,y_test_pred)

print(f"The accuracy for the model is {accu}")

The accuracy for the model is 0.69012


# Finding best hyperparameters using the randomized searchcv

In [ ]:
random_grid = {'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400],
               'max_features': ['auto', 'sqrt'],
               'max_depth': [10, 20, 30, 40, 50, 60, 70]
               'min_samples_split': [2, 5, 10,12,15,18,20],
               'min_samples_leaf': [1, 2, 4],
               'bootstrap': [True, False]}
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
rf_random.fit(X_train,y_train)


In [ ]:
rf_random.best_params_

In [19]:
rfc_model = RandomForestClassifier(n_estimators=800,max_features="auto",
                                  max_depth=30,min_samples_split=12,min_samples_leaf=4,bootstrap=True)
rfc_model.fit(X_train,y_train)

C:\Users\Student\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(max_depth=30, max_features='auto', min_samples_leaf=4,
                       min_samples_split=12, n_estimators=800)

In [25]:
#best model on the validation data
y_valid_pred = rfc_model.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.69492


In [20]:
#best model on the test data
y_test_pred = rfc_model.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.68752


In [21]:
# Confusion matrx for the model
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[ 2528    37  1852]
 [  472  4392  2373]
 [ 1356  1722 10268]]


In [22]:
#Classification Report for the model
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.58      0.57      0.58      4417
           1       0.71      0.61      0.66      7237
           2       0.71      0.77      0.74     13346

    accuracy                           0.69     25000
   macro avg       0.67      0.65      0.66     25000
weighted avg       0.69      0.69      0.69     25000

