In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.model_selection import train_test_split

In [4]:
#Reading data without outliers
df = pd.read_csv('credit_data_process-2.csv')
df.head()

Unnamed: 0  Month  Occupation  Type_of_Loan  Credit_Mix  \
0           1      2          12           128           1   
1           2      6          12           128           1   
2           3      0          12           128           1   
3           4      7          12           128           1   
4           5      5          12           128           1   

   Payment_of_Min_Amount  Payment_Behaviour  Credit_Score   Age  \
0                      1                  4             0  23.0   
1                      1                  5             0   0.0   
2                      1                  6             0  23.0   
3                      1                  2             0  23.0   
4                      1                  0             0  23.0   

   Annual_Income  ...  Delay_from_due_date  Num_of_Delayed_Payment  \
0       19114.12  ...                  0.0               31.033317   
1       19114.12  ...                  3.0                7.000000   
2       19114.12  ...                  5.0                4.000000   
3       19114.12  ...                  6.0               31.033317   
4       19114.12  ...                  8.0                4.000000   

   Changed_Credit_Limit  Num_Credit_Inquiries  Outstanding_Debt  \
0             11.270000                   4.0            809.98   
1             10.389016                   4.0            809.98   
2              6.270000                   4.0            809.98   
3             11.270000                   4.0            809.98   
4              9.270000                   4.0            809.98   

   Credit_Utilization_Ratio  Total_EMI_per_month  Amount_invested_monthly  \
0                 31.944960            49.574949               118.280222   
1                 28.609352            49.574949                81.699521   
2                 31.377862            49.574949               199.458074   
3                 24.797347            49.574949                41.420153   
4                 27.262259            49.574949                62.430172   

   Monthly_Balance  Credit_History_Months  
0       284.629163             220.840847  
1       331.209863             267.000000  
2       223.451310             268.000000  
3       341.489231             269.000000  
4       340.479212             270.000000  

[5 rows x 25 columns]

In [5]:
df = df.drop(['Unnamed: 0'],axis=1)

In [6]:
# Selecting Top 10 features from the feature selection
# Top 10 features
# 1. Outstanding_Debt  
# 2. Annual_Income
# 3. Total_EMI_per_month 
# 4. Type_of_Loan
# 5. Interest_Rate
# 6. Credit_Mix
# 7. Delay_from_due_date  
# 8. Num_Credit_Inquiries
# 9. Payment_of_Min_Amount 
# 10. Num_Credit_Card 

In [7]:
df_1 = df[['Type_of_Loan', 'Credit_Mix', 'Annual_Income', 'Monthly_Inhand_Salary',
       'Num_Credit_Card', 'Interest_Rate', 'Delay_from_due_date',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Total_EMI_per_month','Credit_Score']]

In [8]:
X = df_1.drop(['Credit_Score'],axis=1)
y = df_1['Credit_Score']

In [9]:
#Min Max scaling 
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
model = scalar.fit(X)
scaled_X = model.transform(X)
scaled_X


array([[0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       [0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       [0.02045055, 0.33333333, 0.08770105, ..., 0.22222222, 0.20365971,
        0.13863216],
       ...,
       [0.10912286, 0.33333333, 0.23629269, ..., 0.16666667, 0.12629543,
        0.09816544],
       [0.10912286, 0.33333333, 0.23629269, ..., 0.16666667, 0.12629543,
        0.09816544],
       [0.10912286, 0.33333333, 0.22123968, ..., 0.16666667, 0.12629543,
        0.09816544]])

In [10]:
#splitting data into train,validation and test datasets
X_train, X_rem, y_train, y_rem = train_test_split(scaled_X,y, train_size=0.5,random_state=42)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5,random_state=42)

In [10]:
!pip install xgboost

     ---------------------------------------- 89.1/89.1 MB 3.2 MB/s eta 0:00:00



[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [29]:
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import xgboost as xgb
xgb_model = xgb.XGBClassifier()

In [10]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [11]:
#model on the validation dataset
y_valid_pred = xgb_model.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.74988


In [12]:
#model on the test dataset
y_test_pred = xgb_model.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)
print(f"The accuracy of the model is {acc}")


The accuracy of the model is 0.7436


## finding hyperparameters using grid search 

In [ ]:

random_grid = { 'max_depth': [3, 5, 6, 10, 15, 20],
           'learning_rate': [0.01, 0.1, 0.2, 0.3],
           'subsample': np.arange(0.5, 1.0, 0.1),
           'colsample_bytree': np.arange(0.4, 1.0, 0.1),
           'colsample_bylevel': np.arange(0.4, 1.0, 0.1),
           'n_estimators': [100, 500, 1000]}

rf_random = RandomizedSearchCV(estimator = xgb_model, param_distributions = random_grid,
               n_iter = 100, cv = 5, verbose=2, random_state=35, n_jobs = -1)
rf_random.fit(X_train,y_train)


In [ ]:
rf_random.best_params_

In [12]:
# best model on the validation data
xgb =  xgb.XGBClassifier(max_depth=10,learning_rate=0.1,subsample=0.6,colsample_bytree=0.6,colsample_bylevel=0.7,n_estimators=500)
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=0.7, colsample_bynode=1, colsample_bytree=0.6,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=10, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=500, n_jobs=0,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto', ...)

In [14]:
# best model on the test data
y_test_pred = xgb.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)
print(f"The accuracy of the model is {acc}")


The accuracy of the model is 0.7752


In [15]:
# Confusion matrx for the model
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[ 3133    10  1274]
 [   49  5637  1551]
 [ 1042  1694 10610]]


In [16]:
#Classification Report for the model
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.74      0.71      0.73      4417
           1       0.77      0.78      0.77      7237
           2       0.79      0.79      0.79     13346

    accuracy                           0.78     25000
   macro avg       0.77      0.76      0.76     25000
weighted avg       0.77      0.78      0.77     25000



# Pca model

In [21]:
#Reading pca data 
df = pd.read_csv('Credit_data_PCA.csv')
df.head()

Unnamed: 0         0         1         2         3         4         5  \
0           0 -0.136363 -0.370934  0.041678  0.263842 -0.222105  0.292258   
1           1 -0.226325 -0.463382  0.151887  0.296798  0.345578  0.304052   
2           2 -0.273298 -0.478896  0.422737  0.295270 -0.517704  0.286965   
3           3 -0.126936 -0.375277 -0.303028  0.312867  0.500363  0.306469   
4           4 -0.337219 -0.249693 -0.537153  0.358871  0.219459  0.308859   

          6         7         8  ...        10        11        12        13  \
0  0.251458 -0.438477 -0.190560  ...  0.547227 -0.097278 -0.341116 -0.124602   
1  0.211837 -0.472029 -0.316839  ... -0.020493 -0.073904 -0.188365 -0.469507   
2  0.194752 -0.482383 -0.322554  ... -0.117989  0.019139 -0.105781 -0.162512   
3  0.272134 -0.428103 -0.231405  ...  0.576941  0.048185 -0.210290 -0.179118   
4  0.244402 -0.453667 -0.368670  ... -0.019088  0.321884 -0.029550 -0.192756   

         14        15        16        17        18  Credit_Score  
0 -0.107184 -0.040613 -0.066402  0.042967  0.056982             0  
1  0.041760 -0.076142 -0.225868 -0.041018  0.090555             0  
2 -0.098846 -0.021087 -0.085814 -0.016029  0.084190             0  
3  0.028326 -0.181783 -0.088332  0.009019  0.133855             0  
4 -0.054961 -0.077647 -0.081890 -0.034598  0.105237             0  

[5 rows x 21 columns]

In [22]:
X = df.drop(['Credit_Score','Unnamed: 0'],axis=1)
y = df['Credit_Score']

In [23]:
#splitting data into train,validation and test datasets
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.5,random_state=42)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5,random_state=42)
# shapes of train,validation and  test split
print(X_train.shape), print(y_train.shape)
print(X_valid.shape), print(y_valid.shape)
print(X_test.shape), print(y_test.shape)

(49999, 19)
(49999,)
(25000, 19)
(25000,)
(25000, 19)
(25000,)


(None, None)

In [24]:
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', ...)

In [25]:
#model on the validation dataset
y_valid_pred = xgb_model.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.68384


In [26]:
#model on the test dataset
y_test_pred = xgb_model.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)
print(f"The accuracy of the model is {acc}")


The accuracy of the model is 0.67856


# finding best parameters using grid search

In [ ]:

random_grid = { 'max_depth': [3, 5, 6, 10, 15, 20],
           'learning_rate': [0.01, 0.1, 0.2, 0.3],
           'subsample': np.arange(0.5, 1.0, 0.1),
           'colsample_bytree': np.arange(0.4, 1.0, 0.1),
           'colsample_bylevel': np.arange(0.4, 1.0, 0.1),
           'n_estimators': [100, 500, 1000]}

xg_random = RandomizedSearchCV(estimator = xgb_model, param_distributions = random_grid,
               n_iter = 100, cv = 5, verbose=2, random_state=35, n_jobs = -1)
xg_random.fit(X_train,y_train)


In [ ]:
xg_random.best_params_

In [31]:
# best model on the validation data
xgb_gr =  xgb.XGBClassifier(max_depth=10,learning_rate=0.1,subsample=0.6,colsample_bytree=0.6,colsample_bylevel=0.7,n_estimators=500)
xgb_gr.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=0.7, colsample_bynode=1, colsample_bytree=0.6,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.1, max_bin=256,
              max_cat_threshold=64, max_cat_to_onehot=4, max_delta_step=0,
              max_depth=10, max_leaves=0, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=500, n_jobs=0,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto', ...)

In [33]:
#model on the validation dataset
y_valid_pred = xgb_gr.predict(X_valid)
acc = accuracy_score(y_valid,y_valid_pred)

print(f"The accuracy for the model is {acc}")

The accuracy for the model is 0.6924


In [32]:
# best model on the test data
y_test_pred = xgb_gr.predict(X_test)
acc = accuracy_score(y_test,y_test_pred)
print(f"The accuracy of the model is {acc}")


The accuracy of the model is 0.68372


In [33]:
# Confusion matrx for the model
cm = confusion_matrix(y_test, y_test_pred)
print(cm)

[[ 2326    82  2009]
 [  375  4505  2357]
 [ 1236  1848 10262]]


In [34]:
#Classification Report for the model
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       0.59      0.53      0.56      4417
           1       0.70      0.62      0.66      7237
           2       0.70      0.77      0.73     13346

    accuracy                           0.68     25000
   macro avg       0.66      0.64      0.65     25000
weighted avg       0.68      0.68      0.68     25000

